server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/levi_springboot
    username: root
    password: root
    minIdle: 1000
    initialSize: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid.stat.mergeSql=true;druid.stat.slowSqlMillis: 5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true
logging:
  config: classpath:config/log4j2.xml
