server:
  port: 8888
spring:
  liquibase:
    check-change-log-location: true   #检查存储变化的文件是否存在
    drop-first: false
    enabled: true
    change-log: classpath:/liqubase/changeLog.xml
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/levi_springboot?serverTimezone=UTC
      username: root
      password: root
      minIdle: 1000
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 600
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 40000
      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
  application:
    name: levi-service-manage-cms
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://${host.ip:127.0.0.1}:8761/admin/

logging:
  config: classpath:config/log4j2.xml


eureka:
  client:
    registerWithEureka: true  #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #服务发现开关
      #defaultZone: ${EUREKA_SERVER:http://eureka01:50101/eureka/,http://eureka02:50102/eureka/}
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuato/health
      management.context-path: /actuator

mybatis:
  mapper-locations: classpath:com/levi/springboot/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

management:
  endpoints:
    web:
      exposure:
        include: "*"


  info:
    git:
      mode: full
