server:
  port: 8888
spring:
  datasource:
    username: ${db.username:root}
    password: ${db.password:123456}
    url: ${db.data.url:jdbc:mysql://${db.url:localhost:3306}/evo_interface?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8}
    driver-class-name: ${db.driver:com.mysql.jdbc.Driver}
    hikari:
      idle-timeout: 80000
      connection-timeout: 80000
      max-lifetime: 80000
      minimum-idle: 10
      maximum-pool-size: 30
      leak-detection-threshold: 100000
  flyway:
    enabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  executor-type: simple
  global-config.db-config.id-type: AUTO
  #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
  global-config.db-config.field-strategy: NOT_NULL
  global-config.db-config.refresh: true
  #是否缓存 Sql 解析，默认不缓存。
  global-config.db-config.sql-parser-cache: true
  # 原生配置
  #开启自动驼峰命名规则（camel case）映射
  configuration.mapUnderscoreToCamelCase: true
  global-config.db-config.db-column-underline: true
  #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true。
  configuration.cache-enabled: false
  #该配置可指定 MyBatis 是否并且如何来自动映射数据表字段与对象的属性，
  #总共有 3 种可选值NONE：不启用自动映射;PARTIAL：只对非嵌套的 resultMap 进行自动映射;FULL：对所有的 resultMap 都进行自动映射
  configuration.auto-mapping-behavior: partial
  #该配置可指定 MyBatis 在自动映射过程中遇到未知列或者未知属性时如何处理
  #NONE：不做任何处理 (默认值);WARNING：以日志的形式打印相关警告信息;FAILING：当作映射失败处理，并抛出异常和详细信息
  configuration.auto-mapping-unknown-column-behavior: WARNING
  #结果为null时是否进行set，不开启则返回null，开启返回new Object，但无值
  configuration.call-setters-on-nulls: false
  type-aliases-super-type: java.lang.Object
  global-config.db-config.db-type: MYSQL


warehouseId: 1
warehouseCode:
waitSecond: 10000
hoist.waitTime: 5000
backArea: FreeParkingArea
hoist:
  request:
    url: http://172.28.200.99:10090


